version: '3.8'

services:
  web:
    build: .
    ports:
      - "8899:5000"
    depends_on:
      - db
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:password@db:5432/mapdb

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: mapdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
