# Stage 1: Build React App
FROM node:18-alpine

WORKDIR /app

# Install dependencies
COPY client/package*.json ./
RUN npm install

# Copy the rest of the application code
COPY client/ ./

# Expose the development server port
EXPOSE 80
ENV PORT=80

# Start the React development server
CMD npm start --host 0.0.0.0 --port 80 --disableHostCheck true
