version: '3.8'

services:
  backend:
    build:
        context: .
        dockerfile: Dockerfile.backend
    ports:
      - "8081:8081"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - DATABASE_URL=postgresql://postgres:password@db:5432/mapdb

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev.frontend
    ports:
      - "8080:80"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://localhost:8081
      - WDS_SOCKET_PORT=8080  # Redirection port for Webpack Dev Server

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: mapdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
